### ISSUE TITLE
Issue with Popup LOV in APEX 5

### ISSUE THREAD

**Issue by maxhorizon** [Dani3lSun/apex-plugin-clockpicker#5]
There is a small issue when using clocpicked with Popup LOV in the same page. The plugin adds the following unnecessary CSS rules to Popup LOV item in APEX 5 UT:

fieldset {
    border: 1px solid #c0c0c0;
    margin: 0 2px;
    padding: .35em .625em .75em;
}

![image](https://cloud.githubusercontent.com/assets/165365/12029785/d72f53cc-ae0c-11e5-8dce-f12c7e26bc89.png)

**Comment by Dani3lSun** [comment]
Hi maxhorizon,
fixed the issue and published new release v1.5. Thanks for the hint!

**Comment by maxhorizon** [comment]
Hi Dani,

I think I am still facing the issue:

![image](https://cloud.githubusercontent.com/assets/165365/12077580/4f66bb12-b206-11e5-8225-844d2435d9a5.png)

Am I missing something?

I re-installed the plugin, copied the updated files to the server.
I am using the following prefix:

#IMAGE_PREFIX#custom_plugins/clockpicker/

Am I missing something?

Regards,
Salim

**Comment by Dani3lSun** [comment]
Hi @maxhorizon 
I tested version 1.5 on apex.oracle.com and installed it fresh on a local app, I don´t have that issue any more, see:

<img width="457" alt="screen_01" src="https://cloud.githubusercontent.com/assets/698942/12078240/16af9e0c-b20a-11e5-8623-848967b1aee2.png">

Your prefix looks also fine, directly under your 
#IMAGE_PREFIX#custom_plugins/clockpicker/ you should have the css and js folder. Maybe a permission problem? Uploaded the files as root and web server can´t read it? That would explain the 404 error...

Regards
Daniel
